$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_kernelridge
display_name: train KernelRidge model
version: 1

code: ./train_kernelridge
additional_includes:
    - data_prep_func.py
    - train_model_func.py

inputs:
  prep_data_dir:
    type: uri_folder
  kernel:
    type: string
    default: linear

outputs:
  results_dir:
    type: uri_folder

environment: azureml:AzureML-sklearn-1.5@latest
#azureml:sklearn-mltable:0.1.0

command: >-
  python train_kernelridge.py
  --prep_data_dir ${{inputs.prep_data_dir}}
  --results_dir ${{outputs.results_dir}}
  --kernel ${{inputs.kernel}}
